name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install
      run: npm install
    - name: set config
      run: |
        git config --global user.email "vividtravelandtours.noreply@gmail.com"
        git config --global user.name "vividtravelandtours"
    - name: Build
      run: npm run build
    - name: Deploy
      run: npm run deploy
